# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c65f05495c904c9c73bbde0895174cb1a342ab3720eba645c57f1c4929f0e3f8176f377700d81a84922c7f813de7e304a961b17c180f739975694180a87666b9

test:
  secret_key_base: 161e8b77c9ac3fd8654d9627f92db3bbf1403e198fb17019d8a186ef05421a2960c789257dbaf3b66eda882b5cdc388597d1f8e4ef319f73fb05ac29500f0814

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
